FROM ethereum/client-go

USER root

RUN apk add --no-cache bash

ADD ./local-dev-net /opt/ethereum

WORKDIR /opt/ethereum

VOLUME /opt/.blockchain

ENTRYPOINT ["./run-geth.sh"]

CMD ["-d", "/opt/.blockchain"]